# Name of the feeder
name: LeakFeeder
# Leaks Folder to parse and send to AIL
leaks_folder: Leaks_Folder
# Output Folder of unprocessed split files
out_folder: Unprocessed_Leaks
# Chunks size of split files
chunks: 100000
# API key for AIL authentication
api_key: <your AIL API key>
# AIL API URL
ail_url: https://<your AIL server>:<AIL port>/api/v1
# Uniq identifier of the feeder
uuid: 17450648-9581-42a6-b7c4-28c13f4664bf
# Time sleep between API calls in seconds
wait: 0.5